# Stage 1: Build Flutter Web
FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app
COPY . .

# Faz o download das dependências do Flutter
RUN flutter pub get

# Compila o Flutter para web (usando o renderer padrão canvas kit)
RUN flutter create . --platforms web
RUN flutter build web --release

# Stage 2: Serve Nginx
FROM nginx:alpine

# Remove o HTML padrão do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos gerados pelo Flutter
COPY --from=build /app/build/web /usr/share/nginx/html

# Expõe a porta 80 do nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
