tunnel: e8a0856b-ac03-471b-9c3e-77ad158687b8
credentials-file: /Users/rhmorais/.cloudflared/e8a0856b-ac03-471b-9c3e-77ad158687b8.json

ingress:
  - hostname: api.rhprogramer.com.br
    service: http://localhost:8080
  - hostname: defesa.rhprogramer.com.br
    service: http://localhost:8085
  - hostname: painel.rhprogramer.com.br
    service: http://localhost:8085
  - hostname: fotos.rhprogramer.com.br
    service: http://localhost:9000
  - service: http_status:404
